# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hoosiki/Documents/geant4/example

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hoosiki/Documents/geant4/example

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hoosiki/Documents/geant4/example/CMakeFiles /Users/hoosiki/Documents/geant4/example/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hoosiki/Documents/geant4/example/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ex

# Build rule for target.
ex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ex
.PHONY : ex

# fast build rule for target.
ex/fast:
	$(MAKE) -f CMakeFiles/ex.dir/build.make CMakeFiles/ex.dir/build
.PHONY : ex/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

example.o: example.cc.o
.PHONY : example.o

# target to build an object file
example.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cc.o
.PHONY : example.cc.o

example.i: example.cc.i
.PHONY : example.i

# target to preprocess a source file
example.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cc.i
.PHONY : example.cc.i

example.s: example.cc.s
.PHONY : example.s

# target to generate assembly for a file
example.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.cc.s
.PHONY : example.cc.s

src/B5PrimaryGeneratorAction.o: src/B5PrimaryGeneratorAction.cc.o
.PHONY : src/B5PrimaryGeneratorAction.o

# target to build an object file
src/B5PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/B5PrimaryGeneratorAction.cc.o
.PHONY : src/B5PrimaryGeneratorAction.cc.o

src/B5PrimaryGeneratorAction.i: src/B5PrimaryGeneratorAction.cc.i
.PHONY : src/B5PrimaryGeneratorAction.i

# target to preprocess a source file
src/B5PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/B5PrimaryGeneratorAction.cc.i
.PHONY : src/B5PrimaryGeneratorAction.cc.i

src/B5PrimaryGeneratorAction.s: src/B5PrimaryGeneratorAction.cc.s
.PHONY : src/B5PrimaryGeneratorAction.s

# target to generate assembly for a file
src/B5PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/B5PrimaryGeneratorAction.cc.s
.PHONY : src/B5PrimaryGeneratorAction.cc.s

src/ExN06PhysicsList.o: src/ExN06PhysicsList.cc.o
.PHONY : src/ExN06PhysicsList.o

# target to build an object file
src/ExN06PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/ExN06PhysicsList.cc.o
.PHONY : src/ExN06PhysicsList.cc.o

src/ExN06PhysicsList.i: src/ExN06PhysicsList.cc.i
.PHONY : src/ExN06PhysicsList.i

# target to preprocess a source file
src/ExN06PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/ExN06PhysicsList.cc.i
.PHONY : src/ExN06PhysicsList.cc.i

src/ExN06PhysicsList.s: src/ExN06PhysicsList.cc.s
.PHONY : src/ExN06PhysicsList.s

# target to generate assembly for a file
src/ExN06PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/ExN06PhysicsList.cc.s
.PHONY : src/ExN06PhysicsList.cc.s

src/ExN06PhysicsListMessenger.o: src/ExN06PhysicsListMessenger.cc.o
.PHONY : src/ExN06PhysicsListMessenger.o

# target to build an object file
src/ExN06PhysicsListMessenger.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/ExN06PhysicsListMessenger.cc.o
.PHONY : src/ExN06PhysicsListMessenger.cc.o

src/ExN06PhysicsListMessenger.i: src/ExN06PhysicsListMessenger.cc.i
.PHONY : src/ExN06PhysicsListMessenger.i

# target to preprocess a source file
src/ExN06PhysicsListMessenger.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/ExN06PhysicsListMessenger.cc.i
.PHONY : src/ExN06PhysicsListMessenger.cc.i

src/ExN06PhysicsListMessenger.s: src/ExN06PhysicsListMessenger.cc.s
.PHONY : src/ExN06PhysicsListMessenger.s

# target to generate assembly for a file
src/ExN06PhysicsListMessenger.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/ExN06PhysicsListMessenger.cc.s
.PHONY : src/ExN06PhysicsListMessenger.cc.s

src/MagneticField.o: src/MagneticField.cc.o
.PHONY : src/MagneticField.o

# target to build an object file
src/MagneticField.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/MagneticField.cc.o
.PHONY : src/MagneticField.cc.o

src/MagneticField.i: src/MagneticField.cc.i
.PHONY : src/MagneticField.i

# target to preprocess a source file
src/MagneticField.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/MagneticField.cc.i
.PHONY : src/MagneticField.cc.i

src/MagneticField.s: src/MagneticField.cc.s
.PHONY : src/MagneticField.s

# target to generate assembly for a file
src/MagneticField.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/MagneticField.cc.s
.PHONY : src/MagneticField.cc.s

src/exampleActionInitialization.o: src/exampleActionInitialization.cc.o
.PHONY : src/exampleActionInitialization.o

# target to build an object file
src/exampleActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleActionInitialization.cc.o
.PHONY : src/exampleActionInitialization.cc.o

src/exampleActionInitialization.i: src/exampleActionInitialization.cc.i
.PHONY : src/exampleActionInitialization.i

# target to preprocess a source file
src/exampleActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleActionInitialization.cc.i
.PHONY : src/exampleActionInitialization.cc.i

src/exampleActionInitialization.s: src/exampleActionInitialization.cc.s
.PHONY : src/exampleActionInitialization.s

# target to generate assembly for a file
src/exampleActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleActionInitialization.cc.s
.PHONY : src/exampleActionInitialization.cc.s

src/exampleDetectorConstruction.o: src/exampleDetectorConstruction.cc.o
.PHONY : src/exampleDetectorConstruction.o

# target to build an object file
src/exampleDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleDetectorConstruction.cc.o
.PHONY : src/exampleDetectorConstruction.cc.o

src/exampleDetectorConstruction.i: src/exampleDetectorConstruction.cc.i
.PHONY : src/exampleDetectorConstruction.i

# target to preprocess a source file
src/exampleDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleDetectorConstruction.cc.i
.PHONY : src/exampleDetectorConstruction.cc.i

src/exampleDetectorConstruction.s: src/exampleDetectorConstruction.cc.s
.PHONY : src/exampleDetectorConstruction.s

# target to generate assembly for a file
src/exampleDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleDetectorConstruction.cc.s
.PHONY : src/exampleDetectorConstruction.cc.s

src/exampleEventAction.o: src/exampleEventAction.cc.o
.PHONY : src/exampleEventAction.o

# target to build an object file
src/exampleEventAction.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleEventAction.cc.o
.PHONY : src/exampleEventAction.cc.o

src/exampleEventAction.i: src/exampleEventAction.cc.i
.PHONY : src/exampleEventAction.i

# target to preprocess a source file
src/exampleEventAction.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleEventAction.cc.i
.PHONY : src/exampleEventAction.cc.i

src/exampleEventAction.s: src/exampleEventAction.cc.s
.PHONY : src/exampleEventAction.s

# target to generate assembly for a file
src/exampleEventAction.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleEventAction.cc.s
.PHONY : src/exampleEventAction.cc.s

src/examplePrimaryGeneratorAction.o: src/examplePrimaryGeneratorAction.cc.o
.PHONY : src/examplePrimaryGeneratorAction.o

# target to build an object file
src/examplePrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/examplePrimaryGeneratorAction.cc.o
.PHONY : src/examplePrimaryGeneratorAction.cc.o

src/examplePrimaryGeneratorAction.i: src/examplePrimaryGeneratorAction.cc.i
.PHONY : src/examplePrimaryGeneratorAction.i

# target to preprocess a source file
src/examplePrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/examplePrimaryGeneratorAction.cc.i
.PHONY : src/examplePrimaryGeneratorAction.cc.i

src/examplePrimaryGeneratorAction.s: src/examplePrimaryGeneratorAction.cc.s
.PHONY : src/examplePrimaryGeneratorAction.s

# target to generate assembly for a file
src/examplePrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/examplePrimaryGeneratorAction.cc.s
.PHONY : src/examplePrimaryGeneratorAction.cc.s

src/exampleRunAction.o: src/exampleRunAction.cc.o
.PHONY : src/exampleRunAction.o

# target to build an object file
src/exampleRunAction.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleRunAction.cc.o
.PHONY : src/exampleRunAction.cc.o

src/exampleRunAction.i: src/exampleRunAction.cc.i
.PHONY : src/exampleRunAction.i

# target to preprocess a source file
src/exampleRunAction.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleRunAction.cc.i
.PHONY : src/exampleRunAction.cc.i

src/exampleRunAction.s: src/exampleRunAction.cc.s
.PHONY : src/exampleRunAction.s

# target to generate assembly for a file
src/exampleRunAction.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/exampleRunAction.cc.s
.PHONY : src/exampleRunAction.cc.s

src/parallel_Pipe.o: src/parallel_Pipe.cc.o
.PHONY : src/parallel_Pipe.o

# target to build an object file
src/parallel_Pipe.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/parallel_Pipe.cc.o
.PHONY : src/parallel_Pipe.cc.o

src/parallel_Pipe.i: src/parallel_Pipe.cc.i
.PHONY : src/parallel_Pipe.i

# target to preprocess a source file
src/parallel_Pipe.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/parallel_Pipe.cc.i
.PHONY : src/parallel_Pipe.cc.i

src/parallel_Pipe.s: src/parallel_Pipe.cc.s
.PHONY : src/parallel_Pipe.s

# target to generate assembly for a file
src/parallel_Pipe.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/parallel_Pipe.cc.s
.PHONY : src/parallel_Pipe.cc.s

src/smdHit.o: src/smdHit.cc.o
.PHONY : src/smdHit.o

# target to build an object file
src/smdHit.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/smdHit.cc.o
.PHONY : src/smdHit.cc.o

src/smdHit.i: src/smdHit.cc.i
.PHONY : src/smdHit.i

# target to preprocess a source file
src/smdHit.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/smdHit.cc.i
.PHONY : src/smdHit.cc.i

src/smdHit.s: src/smdHit.cc.s
.PHONY : src/smdHit.s

# target to generate assembly for a file
src/smdHit.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/smdHit.cc.s
.PHONY : src/smdHit.cc.s

src/smdSD.o: src/smdSD.cc.o
.PHONY : src/smdSD.o

# target to build an object file
src/smdSD.cc.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/smdSD.cc.o
.PHONY : src/smdSD.cc.o

src/smdSD.i: src/smdSD.cc.i
.PHONY : src/smdSD.i

# target to preprocess a source file
src/smdSD.cc.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/smdSD.cc.i
.PHONY : src/smdSD.cc.i

src/smdSD.s: src/smdSD.cc.s
.PHONY : src/smdSD.s

# target to generate assembly for a file
src/smdSD.cc.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/src/smdSD.cc.s
.PHONY : src/smdSD.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ex"
	@echo "... example"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... src/B5PrimaryGeneratorAction.o"
	@echo "... src/B5PrimaryGeneratorAction.i"
	@echo "... src/B5PrimaryGeneratorAction.s"
	@echo "... src/ExN06PhysicsList.o"
	@echo "... src/ExN06PhysicsList.i"
	@echo "... src/ExN06PhysicsList.s"
	@echo "... src/ExN06PhysicsListMessenger.o"
	@echo "... src/ExN06PhysicsListMessenger.i"
	@echo "... src/ExN06PhysicsListMessenger.s"
	@echo "... src/MagneticField.o"
	@echo "... src/MagneticField.i"
	@echo "... src/MagneticField.s"
	@echo "... src/exampleActionInitialization.o"
	@echo "... src/exampleActionInitialization.i"
	@echo "... src/exampleActionInitialization.s"
	@echo "... src/exampleDetectorConstruction.o"
	@echo "... src/exampleDetectorConstruction.i"
	@echo "... src/exampleDetectorConstruction.s"
	@echo "... src/exampleEventAction.o"
	@echo "... src/exampleEventAction.i"
	@echo "... src/exampleEventAction.s"
	@echo "... src/examplePrimaryGeneratorAction.o"
	@echo "... src/examplePrimaryGeneratorAction.i"
	@echo "... src/examplePrimaryGeneratorAction.s"
	@echo "... src/exampleRunAction.o"
	@echo "... src/exampleRunAction.i"
	@echo "... src/exampleRunAction.s"
	@echo "... src/parallel_Pipe.o"
	@echo "... src/parallel_Pipe.i"
	@echo "... src/parallel_Pipe.s"
	@echo "... src/smdHit.o"
	@echo "... src/smdHit.i"
	@echo "... src/smdHit.s"
	@echo "... src/smdSD.o"
	@echo "... src/smdSD.i"
	@echo "... src/smdSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

